export const FAKE_ACTION = 'FAKE_ACTION';

export const INCREMENT_VERSE = 'INCREMENT_VERSE';
export const DECREMENT_VERSE = 'DECREMENT_VERSE';

export const GET_BIBLE_ESV_REQUEST = 'GET_BIBLE_ESV_REQUEST';
export const GET_BIBLE_ESV_SUCCESS = 'GET_BIBLE_ESV_SUCCESS';
export const GET_BIBLE_ESV_FAILURE = 'GET_BIBLE_ESV_FAILURE';
export const LOAD_BIBLE_VARIABLES = 'LOAD_BIBLE_VARIABLES';

export const GET_PIC_REQUEST = 'GET_PIC_REQUEST';
export const GET_PIC_SUCCESS = 'GET_PIC_SUCCESS';
export const GET_PIC_FAILURE = 'GET_PIC_FAILURE';

export const UPDATE_POST = 'UPDATE_POST';
export const ADD_POST = 'ADD_POST';