export const FAKE_ACTION = 'FAKE_ACTION';

export const INCREMENT_VERSE = 'INCREMENT_VERSE';
export const DECREMENT_VERSE = 'DECREMENT_VERSE';
export const SET_VERSE = 'SET_VERSE';

export const GET_BIBLE_ESV_REQUEST = 'GET_BIBLE_ESV_REQUEST';
export const GET_BIBLE_ESV_SUCCESS = 'GET_BIBLE_ESV_SUCCESS';
export const GET_BIBLE_ESV_FAILURE = 'GET_BIBLE_ESV_FAILURE';
export const GET_BIBLE_VARIABLE_REQUEST = 'GET_BIBLE_VARIABLE_REQUEST';
export const GET_BIBLE_VARIABLE_SUCCESS = 'GET_BIBLE_VARIABLE_SUCCESS';
export const GET_BIBLE_VARIABLE_FAILURE = 'GET_BIBLE_VARIABLE_FAILURE';
export const GET_BIBLE_PLAN_REQUEST = 'GET_BIBLE_PLAN_REQUEST';
export const GET_BIBLE_PLAN_SUCCESS = 'GET_BIBLE_PLAN_SUCCESS';
export const GET_BIBLE_PLAN_FAILURE = 'GET_BIBLE_PLAN_FAILURE';
export const SET_BIBLE_PLAN = 'SET_BIBLE_PLAN';

export const GET_PIC_REQUEST = 'GET_PIC_REQUEST';
export const GET_PIC_SUCCESS = 'GET_PIC_SUCCESS';
export const GET_PIC_FAILURE = 'GET_PIC_FAILURE';

export const UPDATE_POST = 'UPDATE_POST';
export const ADD_POST = 'ADD_POST';